### ISSUE TITLE
Fs.existsSync is not a function

### ISSUE THREAD

**Issue by edy-ap** [Romakita/ts-json-properties#3]
core.js:1350 ERROR Error: Uncaught (in promise): TypeError: Fs.existsSync is not a function
TypeError: Fs.existsSync is not a function
    at Properties.read (properties.js:22)

**Comment by Romakita** [comment]
Hi @edy-ap,
What is your node version ?

**Comment by marmartins** [comment]
Hi Romakite, 
Recently I had the same error using the NodeJS Version [v9.5.0].
