### ISSUE TITLE
EnvValue

### ISSUE THREAD

**Issue by aliciacapgemini** [Romakita/ts-json-properties#4]
Hello,

I am trying to use @EnvValue (expression).

Without defining in path the variable, I found that it does not find the variable. I fix it by concatenating "Default" to its name (would not it be better if they were called the same?).

If I define the variable and also find the variable in the properties.json uses the properties.

How can I use it correctly?

Thanks.

**Comment by Romakita** [comment]
Hi @aliciacapgemini ,
Yes it's a bit weird ... I didn't remember why I do that.

I'll change the behavior. 
See you

**Comment by aliciacapgemini** [comment]
Hi again!

In my controller:

@EnvValue('port')
private port: number;

@Get('prueba')
    prueba(){
        return this.port;
    }

-----------------------
In properties.json
"port": "3001"

-return --> undefined
-----------------------

In properties.json
"portDefault": "3001"

-return --> 3001
-----------------------

In properties.json
"port": "3001"

PATH -> export PORT=3000

-return --> undefined
-----------------------

In properties.json
"portDefault": "3001"

PATH -> export PORT=3000

-return --> 30001
-----------------------

Thank you.

**Comment by Romakita** [comment]
@aliciacapgemini Yes I've change my comment. The envValue decorator is not correctly implemented. I'll fix that ASAP ;)

**Comment by aliciacapgemini** [comment]
@Romakita  It woks in this case:

in properties.json:

"portDefault": "3001",
"port": "PORT"

**Comment by Romakita** [comment]
Fixed :)
